version: '3'
services:

  carpadi-api:
    image: olalekanadebari/carpadi-api:latest
    restart: always
    ports:
      - "8000:8000"
    env_file: .env-new
    volumes:
      - /app/static:/app/src/staticfiles

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=passersby


