# Generated by Django 3.2.4 on 2022-03-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpadi_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transction',
        ),
    ]
