# Generated by Django 3.2.4 on 2022-08-08 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 8, 10, 26, 5793, tzinfo=utc), editable=False),
        ),
    ]
