# Generated by Django 3.2.4 on 2022-03-27 03:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import src.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(
                choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_cash',
            field=models.DecimalField(decimal_places=10, default=2, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='trading_cash',
            field=models.DecimalField(decimal_places=10, default=322, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='unsettled_cash',
            field=models.DecimalField(decimal_places=10, default=3, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawable_cash',
            field=models.DecimalField(decimal_places=10, default=432, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_inspector',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                validators=[src.models.models.validate_inspector],
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 4, 21, 45, 919892, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='merchant',
            field=models.OneToOneField(
                help_text='merchant user wallet that holds monetary balances',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='merchant_wallet',
                to='models.carmerchant',
            ),
        ),
    ]
