# Generated by Django 3.2.4 on 2022-03-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2348129014778, help_text='International format phone number', max_length=15),
            preserve_default=False,
        ),
    ]
