# Generated by Django 3.2.4 on 2022-04-09 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='trade_unit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='trade_units', to='models.tradeunit'
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 13, 49, 3, 667871, tzinfo=utc), editable=False),
        ),
    ]
