# Generated by Django 3.2.4 on 2022-04-11 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 16, 51, 56, 299953, tzinfo=utc), editable=False),
        ),
    ]
