# Generated by Django 3.2.4 on 2022-03-06 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20220305_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('ts_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('merchant', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
