# Generated by Django 3.2.4 on 2022-08-08 15:27

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='max_sale_price',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 15, 57, 22, 907481, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='min_sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='min price at which the car can be sold, given the expenses we already made. this should be determined by calculating how much maintanance is done + total disbursement at the end of trade', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
