# Generated by Django 3.2.4 on 2022-09-02 22:25

import datetime
from decimal import Decimal
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='repair_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 22, 55, 2, 587828, tzinfo=utc), editable=False),
        ),
    ]
