# Generated by Django 3.2.4 on 2022-03-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(editable=False, max_length=6)),
                ('expiry', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('verified', 'Otp verified by user successfully'), ('failed', 'User entered wrong otp until disabled'), ('expired', 'Otp was not entered before it expired'), ('pending', 'Otp is yet to expire or has expired and no one sent a verification request for it')], default='pending', help_text='Keep track of weather the otp was later verified or expired or failed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
