# Generated by Django 3.2.4 on 2022-03-28 05:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20220327_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slots_available', models.IntegerField(default=0)),
                ('slots_purchased', models.IntegerField(default=0)),
                ('return_on_trade', models.DecimalField(decimal_places=10, editable=False, max_digits=10, max_length=10)),
                ('expected_return_on_trade', models.DecimalField(decimal_places=10, editable=False, max_digits=10, max_length=10)),
                ('traded_slots', models.IntegerField(default=0)),
                ('remaining_slots', models.IntegerField(default=0)),
                ('total_slots', models.IntegerField(default=0)),
                ('price_per_slot', models.DecimalField(decimal_places=10, editable=False, max_digits=10, max_length=10)),
                ('trade_status', models.CharField(choices=[('pending', 'Pending review'), ('ongoing', 'Slots are yet to be fully bought'), ('completed', 'Car has been sold and returns sorted to merchants'), ('purchased', 'All slots have been bought by merchants')], max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='models.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], default='deposit', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 5, 52, 52, 662055, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='TradeUnit',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_percentage', models.DecimalField(decimal_places=10, editable=False, max_digits=10, max_length=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='models.carmerchant')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='models.trade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
