# Generated by Django 3.2.4 on 2022-03-06 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20220306_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarMerchant',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bvn', models.CharField(max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('merchant', 'merchant')], default='merchant', max_length=20),
        ),
        migrations.AddField(
            model_name='carmerchant',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='merchant',
            field=models.ForeignKey(
                help_text='Bank account to remit merchant money to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bank_accounts',
                to='models.carmerchant',
            ),
        ),
    ]
