# Generated by Django 3.2.4 on 2022-04-11 16:23

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0002_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 16, 53, 6, 997308, tzinfo=utc),
                                       editable=False),
        ),
    ]
