# Generated by Django 3.2.4 on 2022-09-02 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20220902_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmaintenance',
            name='cost',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 23, 20, 25, 3074, tzinfo=utc), editable=False),
        ),
    ]
