# Generated by Django 3.2.4 on 2022-03-17 17:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20220317_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 7, 20, 401510, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name='TransactionPin',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_serial_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('device_platform', models.CharField(editable=False, max_length=20, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('expired', 'User already deleted device from device management'),
                            ('active', 'Transaction pin is still active'),
                        ],
                        max_length=10,
                    ),
                ),
                ('pin', models.CharField(max_length=4)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='transaction_pins', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
