# Generated by Django 3.2.4 on 2022-03-17 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20220317_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 18, 26, 850683, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transactionpin',
            name='pin',
            field=models.CharField(max_length=200),
        ),
    ]
