# Generated by Django 3.2.4 on 2022-04-12 22:27

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0005_auto_20220412_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='margin',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The profit that was made from car after sales in percentage of the total cost',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 22, 57, 28, 749280, tzinfo=utc), editable=False),
        ),
    ]
