# Generated by Django 3.2.4 on 2022-09-03 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20220903_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='carpadi_trade_rot_percentage',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 7, 17, 788687, tzinfo=utc), editable=False),
        ),
    ]
