# Generated by Django 3.2.4 on 2022-04-04 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20220404_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 22, 19, 8, 581718, tzinfo=utc), editable=False),
        ),
    ]
