# Generated by Django 3.2.4 on 2022-09-04 11:30

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20220903_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeunit',
            name='trade_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='The bonus that the trade unit got if any', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 12, 0, 12, 950825, tzinfo=utc), editable=False),
        ),
    ]
