# Generated by Django 3.2.4 on 2022-03-17 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20220317_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 19, 2, 14, 412456, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('merchant', 'merchant')], default='merchant', max_length=20),
        ),
    ]
