# Generated by Django 3.2.4 on 2022-08-10 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total cost = bought_price + cost_of_repairs + maintenance_cost + misc', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carproduct',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='models.car'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 21, 35, 34, 732965, tzinfo=utc), editable=False),
        ),
    ]
