# Generated by Django 3.2.4 on 2022-04-20 05:18

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models', '0007_auto_20220418_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('lpg', 'LPG'),
                                            ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='Petrol',
                                   max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('failed_inspection', 'Failed Inspection'), ('inspected', 'inspected'),
                                            ('available', 'available for trading and sale'),
                                            ('ongoing_trade', 'Car is an ongoing trade'), ('bought', 'bought'),
                                            ('sold', 'sold'), ('new', 'New car waiting to be inspected')],
                                   default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 5, 47, 12, 850598, tzinfo=utc),
                                       editable=False),
        ),
    ]
