# Generated by Django 3.2.4 on 2022-04-06 11:40

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 12, 10, 58, 553903, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='estimated_return_on_trade',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='max_sale_price',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                help_text='max price at which the car can be sold',
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='min_sale_price',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                help_text='min price at which the car can be sold',
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price_per_slot',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                editable=False,
                help_text='price per slot',
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=0, help_text='slots that are still available for sale'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='return_on_trade',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='trade',
            name='slots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='slots_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradeunit',
            name='estimated_rot',
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal('0'),
                editable=False,
                help_text='the estimated return on trade',
                max_digits=10,
                max_length=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='tradeunit',
            name='slots_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
