# Generated by Django 3.2.4 on 2022-09-05 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20220904_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 11, 9, 54, 834717, tzinfo=utc), editable=False),
        ),
    ]
