# Generated by Django 3.2.4 on 2022-03-18 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20220317_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 12, 11, 59, 536481, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transactionpin',
            name='device_platform',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionpin',
            name='device_serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
