# Generated by Django 3.2.4 on 2022-08-10 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20220810_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproduct',
            name='status',
            field=models.CharField(choices=[('active', 'Car is still in the market'), ('sold', 'Car has been sold'), ('inactive', 'Car has been recalled due to fault or other issues, or just added and not made active yet')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 22, 49, 20, 663767, tzinfo=utc), editable=False),
        ),
    ]
