# Generated by Django 3.2.4 on 2022-04-21 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20220421_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='slots_purchased',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='models.transaction'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='trade_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_unit', to='models.tradeunit'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 3, 54, 33, 838700, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_kind',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('wallet_transfer', 'Wallet Transfer'), ('disbursement', 'Disbursement')], default='deposit', max_length=50),
        ),
    ]
