# Generated by Django 3.2.4 on 2022-04-24 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import src.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20220421_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, validators=[src.models.models.validate_inspector]),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='trade_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='models.tradeunit'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement', to='models.transaction'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 9, 47, 0, 356111, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='models.car'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('ongoing', 'Slots are yet to be fully bought'), ('completed', 'Car has been sold and returns sorted to merchants'), ('purchased', 'All slots have been bought by merchants'), ('closed', 'All slots have been bought by merchants, car has been sold and disbursements made')], default='ongoing', max_length=20),
        ),
    ]
