# Generated by Django 3.2.4 on 2022-09-05 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20220905_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=10, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 11, 17, 35, 918931, tzinfo=utc), editable=False),
        ),
    ]
