# Generated by Django 3.2.4 on 2022-03-22 00:39

import datetime
import decimal

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20220320_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='car_brand',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='models.carbrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spareparts',
            name='estimated_price',
            field=models.DecimalField(decimal_places=10, default=decimal.Decimal(0.00), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spareparts',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 1, 9, 20, 945153, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transactionpin',
            name='status',
            field=models.CharField(choices=[('expired', 'User already deleted device from device management'), ('active', 'Transaction pin is still active'), ('deleted', 'Transaction pin has been deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarMaintainance',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('spare_part', 'Car spare parts i.e brake.'), ('expense', 'other expenses made on the car that doesnt directly relate to a physical parts.')], max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintanances', to='models.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
