# Generated by Django 3.2.4 on 2022-03-22 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20220322_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 1, 10, 1, 648888, tzinfo=utc), editable=False),
        ),
    ]
