# Generated by Django 3.2.4 on 2022-03-20 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20220320_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 7, 44, 20, 598703, tzinfo=utc), editable=False),
        ),
    ]
