# Generated by Django 3.2.4 on 2022-09-05 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20220905_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 11, 25, 9, 103761, tzinfo=utc), editable=False),
        ),
    ]
