# Generated by Django 3.2.4 on 2022-05-04 06:48

import datetime
import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0013_auto_20220503_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 7, 17, 52, 631819, tzinfo=utc), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='spareparts',
            unique_together={('name', 'car_brand')},
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_id', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('bank_name', 'bank_code')},
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='models.banks'
            ),
            preserve_default=False,
        ),
    ]
