# Generated by Django 3.2.4 on 2022-05-06 05:31

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0014_auto_20220504_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_fees',
            field=models.DecimalField(decimal_places=4, default=0.0,
                                      help_text='Transaction fees for withdrawal transactions', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, help_text='An alias for the bank account', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banks',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 6, 1, 27, 598167, tzinfo=utc),
                                       editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_response',
            field=models.JSONField(blank=True, help_text='Transaction response from payment gateway', null=True),
        ),
    ]
