# Generated by Django 3.2.4 on 2022-09-08 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20220907_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 17, 10, 51, 574706, tzinfo=utc), editable=False),
        ),
    ]
