# Generated by Django 3.2.4 on 2022-05-14 08:27

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 8, 57, 53, 113440, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price_per_slot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='price per slot', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
