# Generated by Django 3.2.4 on 2022-05-14 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 22, 50, 5, 502844, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='bts_time',
            field=models.IntegerField(blank=True, default=0, help_text='time taken to buy to sale in days', null=True),
        ),
    ]
