# Generated by Django 3.2.4 on 2022-09-20 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsessions',
            name='device_imei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 21, 42, 9, 713752, tzinfo=utc), editable=False),
        ),
    ]
