# Generated by Django 3.2.4 on 2022-05-14 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_auto_20220514_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 22, 52, 2, 75330, tzinfo=utc), editable=False),
        ),
    ]
