# Generated by Django 3.2.4 on 2022-09-22 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notice_type',
            field=models.CharField(choices=[('transaction_completed', 'Transaction completed'), ('transaction_failed', 'Transaction failed'), ('new_trade', 'New Trade'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('disbursement', 'Disbursement'), ('trade_unit', 'Trade Unit')], max_length=40),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 13, 31, 42, 514291, tzinfo=utc), editable=False),
        ),
    ]
