# Generated by Django 3.2.4 on 2022-09-22 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20220922_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 15, 0, 33, 738994, tzinfo=utc), editable=False),
        ),
    ]
