# Generated by Django 3.2.4 on 2022-09-25 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_auto_20220922_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocuments',
            name='document_type',
            field=models.CharField(choices=[('proof_of_ownership', 'Proof of ownership document'), ('allocation_of_licence_plate', 'Allocation of plate number'), ('vehicle_license', 'Vehicle license'), ('custom_papers_or_purchase_receipt', 'Customs paper if car was imported or Receipt of purchase documents if the car was bought brand new from an accredited dealer'), ('police_CMR', 'Police CMR'), ('insurance', 'Insurance papers'), ('road_worthiness', 'Road worthiness permit')], default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 0, 33, 13, 810301, tzinfo=utc), editable=False),
        ),
    ]
