# Generated by Django 3.2.4 on 2022-10-08 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_auto_20220925_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='cardocuments',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='carfeature',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='carmaintenance',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='carmerchant',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='carproduct',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='disbursement',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='inspections',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='inspectionstage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='loginsessions',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='miscellaneousexpenses',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='spareparts',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='vehicleinfo',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='carmerchant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmerchant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmerchant',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(
                choices=[
                    ('failed_inspection', 'Failed Inspection'),
                    ('inspected', 'inspected'),
                    ('available', 'available for trading and sale'),
                    ('ongoing_trade', 'Car is an ongoing trade'),
                    ('bought', 'bought'),
                    ('sold', 'sold'),
                    ('pending_inspection', 'Inspection is yet to be started but has been assigned'),
                    ('ongoing_inspection', 'Being inspected'),
                    ('new', 'New car waiting to be inspected'),
                    ('archived', 'Archived'),
                ],
                default='new',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='cardocuments',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('proof_of_ownership', 'Proof of ownership document'),
                    ('allocation_of_licence_plate', 'Allocation of plate number'),
                    ('vehicle_license', 'Vehicle license'),
                    (
                        'custom_papers_or_purchase_receipt',
                        'Customs paper if car was imported or Receipt of purchase documents if the car was bought brand new from an accredited dealer',
                    ),
                    ('police_CMR', 'Police CMR'),
                    ('insurance', 'Insurance papers'),
                    ('road_worthiness', 'Road worthiness permit'),
                    ('owner_identification', "Car Owner's document of identity"),
                    ('others', 'Other custom documents that are not required'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 19, 29, 49, 736761, tzinfo=utc), editable=False),
        ),
    ]
