# Generated by Django 3.2.4 on 2022-10-08 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20221008_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 21, 13, 9, 911432, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={'unique': 'A user with that email already exists.'},
                max_length=254,
                unique=True,
                verbose_name='email address',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                error_messages={'unique': 'A user with that phone number already exists.'},
                help_text='International format phone number',
                max_length=15,
                unique=True,
            ),
        ),
    ]
