# Generated by Django 3.2.4 on 2022-05-15 18:51

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 19, 21, 35, 212818, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='return_on_trade',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The actual profit that was made from car ',
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
    ]
