# Generated by Django 3.2.4 on 2022-10-08 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_auto_20221008_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 21, 13, 41, 621828, tzinfo=utc), editable=False),
        ),
    ]
