# Generated by Django 3.2.4 on 2022-10-09 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 19, 50, 33, 522312, tzinfo=utc), editable=False),
        ),
    ]
