# Generated by Django 3.2.4 on 2022-11-05 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='entity_type',
            field=models.CharField(
                choices=[
                    ('car_product', 'Pictures of a car on the sales platform'),
                    ('car', 'car picture'),
                    ('merchant', 'user profile picture'),
                    ('trade', 'Trade pictures of a car'),
                    ('car_inspection_stage', 'Picture taken for a particular stage during inspection'),
                    ('feature', 'Picture of a feature of a car'),
                    ('inspection_report', 'Pdf report of an inspected vehicle'),
                    ('spare_part', 'Images of spare parts'),
                    ('car_docs', 'Credentials and documents attached to the car'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='owners_review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 22, 32, 18, 35982, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='otps',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
