# Generated by Django 3.2.4 on 2022-05-15 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_auto_20220515_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 20, 53, 53, 285659, tzinfo=utc), editable=False),
        ),
    ]
