# Generated by Django 3.2.4 on 2022-11-06 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_auto_20221105_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmerchant',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='carmerchant',
            name='status',
            field=models.CharField(
                choices=[
                    ('disapproved', 'User approval was declined'),
                    ('pending', ' User is pending approval'),
                    ('approved', 'User has been approved'),
                ],
                default=False,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 8, 20, 52, 585550, tzinfo=utc), editable=False),
        ),
    ]
