# Generated by Django 3.2.4 on 2022-11-11 10:34

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields
import src.models.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_auto_20221106_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 11, 4, 30, 964730, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[('admin', 'admin'), ('merchant', 'merchant'), ('car_seller', 'Car seller')], max_length=20
            ),
        ),
        migrations.CreateModel(
            name='CarPurchaseOffer',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licence_plate', models.CharField(max_length=15, validators=[src.models.validators.LicensePlateValidator])),
                ('registeration_state', models.CharField(max_length=40)),
                (
                    'current_usage_timeframe_by_user',
                    models.PositiveIntegerField(help_text='how long has this user used the car in months'),
                ),
                ('mileage', models.PositiveIntegerField(help_text='the current mileage of the car on the dashboard')),
                (
                    'count_of_previous_users',
                    models.PositiveIntegerField(help_text='how many people have previously used this car'),
                ),
                ('custom_papers_availability', models.BooleanField(default=False)),
                (
                    'car_condition',
                    models.CharField(
                        choices=[
                            ('good', 'Car is in good condition'),
                            ('great', 'Car is in great condition'),
                            ('fair', 'Car is fairly good'),
                            ('poor', 'car is not in good condition'),
                        ],
                        max_length=20,
                    ),
                ),
                ('note', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inspection_location', models.CharField(max_length=40)),
                (
                    'contact_preference',
                    models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'Whatsapp')], max_length=100),
                ),
                ('is_negotiable', models.BooleanField()),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sellers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'vehicle_info',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='purchase_offers',
                        to='models.vehicleinfo',
                    ),
                ),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
