# Generated by Django 3.2.4 on 2022-11-11 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_auto_20221111_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 11, 31, 23, 317002, tzinfo=utc), editable=False),
        ),
    ]
