# Generated by Django 3.2.4 on 2022-05-16 03:53

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0034_auto_20220516_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 4, 23, 32, 993867, tzinfo=utc), editable=False),
        ),
    ]
