# Generated by Django 3.2.4 on 2022-05-16 04:07

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0035_alter_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pictures',
        ),
        migrations.AddField(
            model_name='pictures',
            name='entity_type',
            field=models.CharField(
                choices=[('car', 'car picture'), ('merchant', 'user profile picture')], default='car', max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 4, 37, 14, 361918, tzinfo=utc), editable=False),
        ),
    ]
