# Generated by Django 3.2.4 on 2022-05-16 04:13

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0036_auto_20220516_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 4, 42, 34, 484428, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='asset',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
