# Generated by Django 3.2.4 on 2022-12-30 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0037_auto_20221230_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 15, 59, 875864, tzinfo=utc), editable=False),
        ),
    ]
