# Generated by Django 3.2.4 on 2023-01-07 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_alter_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='spec_country',
            new_name='specifications',
        ),
        migrations.AlterField(
            model_name='carproduct',
            name='highlight',
            field=models.CharField(help_text='A short description of the vehicle', max_length=260),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 10, 12, 16, 808651, tzinfo=utc), editable=False),
        ),
    ]
