# Generated by Django 3.2.4 on 2022-05-18 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_auto_20220516_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pictures',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='models.assets'
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 11, 53, 53, 382520, tzinfo=utc), editable=False),
        ),
    ]
