# Generated by Django 3.2.4 on 2022-05-18 11:24

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0039_auto_20220518_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 11, 54, 6, 84269, tzinfo=utc), editable=False),
        ),
    ]
