# Generated by Django 3.2.4 on 2023-02-01 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_auto_20230130_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.vehicleinfo'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 59, 49, 55308, tzinfo=utc), editable=False),
        ),
    ]
