# Generated by Django 3.2.4 on 2023-02-01 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_auto_20230201_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 19, 0, 12, 968522, tzinfo=utc), editable=False),
        ),
    ]
