# Generated by Django 3.2.4 on 2023-02-08 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpurchaseoffer',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.car'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 15, 2, 29, 810384, tzinfo=utc), editable=False),
        ),
    ]
