# Generated by Django 3.2.4 on 2022-05-21 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_auto_20220521_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='transmission_type',
            new_name='transmission',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 18, 2, 24, 574059, tzinfo=utc), editable=False),
        ),
    ]
