# Generated by Django 3.2.4 on 2022-05-21 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_auto_20220521_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 23, 16, 26, 423895, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
