# Generated by Django 3.2.4 on 2023-02-19 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0046_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpurchaseoffer',
            name='deal_preference',
            field=models.CharField(
                choices=[('swap', 'A car for a car'), ('outright', 'Outright buying of car')], default='outright', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 22, 3, 20, 356548, tzinfo=utc), editable=False),
        ),
    ]
