# Generated by Django 3.2.4 on 2022-05-22 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0046_auto_20220522_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='assets',
            name='entity_type',
            field=models.CharField(
                choices=[
                    ('car_product', 'Pictures of a car on the sales platform'),
                    ('car', 'car picture'),
                    ('merchant', 'user profile picture'),
                    ('trade', 'Trade pictures of a car'),
                    ('car_inspection', 'Car inspection pictures'),
                    ('feature', 'Picture of a feature of a car'),
                    ('inspection_report', 'Pdf report of an inspected vehicle'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 9, 39, 48, 115256, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='CarProduct',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=5, editable=False, max_digits=10)),
                (
                    'car',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='models.car'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='models.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
