# Generated by Django 3.2.4 on 2023-02-20 02:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0048_auto_20230220_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpurchaseoffer',
            name='user',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.carsellers'
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 3, 24, 8, 129205, tzinfo=utc), editable=False),
        ),
    ]
