# Generated by Django 3.2.4 on 2022-05-22 10:07

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0048_auto_20220522_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 10, 37, 8, 718382, tzinfo=utc), editable=False),
        ),
    ]
