# Generated by Django 3.2.4 on 2022-05-24 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0050_auto_20220522_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 11, 17, 446694, tzinfo=utc), editable=False),
        ),
    ]
