# Generated by Django 3.2.4 on 2023-02-20 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0052_auto_20230220_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 38, 40, 566450, tzinfo=utc), editable=False),
        ),
    ]
