# Generated by Django 3.2.4 on 2022-05-26 04:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0052_auto_20220526_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 5, 22, 1, 974966, tzinfo=utc), editable=False),
        ),
    ]
