# Generated by Django 3.2.4 on 2023-03-22 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0053_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 48, 27, 289893, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='car_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
