# Generated by Django 3.2.4 on 2022-05-26 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0054_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 6, 11, 45, 579997, tzinfo=utc), editable=False),
        ),
    ]
