# Generated by Django 3.2.4 on 2022-05-27 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0056_auto_20220527_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 10, 51, 49, 287175, tzinfo=utc), editable=False),
        ),
    ]
