# Generated by Django 3.2.4 on 2023-04-10 13:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0056_alter_otp_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlists',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 20, 21, 629589, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='fuel_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
    ]
