# Generated by Django 3.2.4 on 2023-04-28 11:48

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0057_auto_20230410_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 18, 13, 657720, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='waitlists',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
