# Generated by Django 3.2.4 on 2023-04-28 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0058_auto_20230428_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 20, 10, 449179, tzinfo=utc), editable=False),
        ),
    ]
