# Generated by Django 3.2.4 on 2023-04-28 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0060_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 22, 48, 526397, tzinfo=utc), editable=False),
        ),
    ]
