# Generated by Django 3.2.4 on 2022-05-29 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0061_auto_20220528_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='estimated_sales_duration',
            field=models.PositiveIntegerField(default=1, help_text='estimated sales duration in days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 9, 30, 24, 181273, tzinfo=utc), editable=False),
        ),
    ]
