# Generated by Django 3.2.4 on 2023-06-06 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0061_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 23, 1, 34, 834887, tzinfo=utc), editable=False),
        ),
    ]
