# Generated by Django 3.2.4 on 2023-07-14 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0062_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 11, 51, 25, 838783, tzinfo=utc), editable=False),
        ),
    ]
