# Generated by Django 3.2.4 on 2022-05-29 09:01

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0062_auto_20220529_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 9, 31, 45, 348538, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='estimated_sales_duration',
            field=models.PositiveIntegerField(default=30, help_text='estimated sales duration in days'),
        ),
    ]
