# Generated by Django 3.2.4 on 2022-05-29 09:02

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0063_auto_20220529_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 9, 32, 18, 202245, tzinfo=utc), editable=False),
        ),
    ]
