# Generated by Django 3.2.4 on 2022-05-30 00:38

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0067_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 1, 8, 28, 310089, tzinfo=utc), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='transactionpin',
            unique_together={('device_serial_number', 'pin')},
        ),
    ]
