# Generated by Django 3.2.4 on 2022-05-30 00:39

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0068_auto_20220530_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 1, 9, 1, 744771, tzinfo=utc), editable=False),
        ),
    ]
