# Generated by Django 3.2.4 on 2022-06-17 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0073_alter_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 57, 6, 753004, tzinfo=utc), editable=False),
        ),
    ]
