# Generated by Django 3.2.4 on 2022-06-25 11:00

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('models', '0076_auto_20220625_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 11, 30, 56, 397067, tzinfo=utc), editable=False),
        ),
    ]
