# Generated by Django 3.2.4 on 2022-07-23 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0078_auto_20220723_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproduct',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Car is still in the market'),
                    ('sold', 'Car has been sold'),
                    ('inactive', 'Car has been recalled due to fault or other issues'),
                ],
                default='active',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 9, 54, 36, 492087, tzinfo=utc), editable=False),
        ),
    ]
