# Generated by Django 3.2.4 on 2022-07-31 14:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields
import src.models.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0079_auto_20220723_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspections',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owners_name', models.CharField(max_length=100)),
                ('inspection_date', models.DateTimeField()),
                ('owners_phone', models.CharField(max_length=20, validators=[src.models.validators.PhoneNumberValidator])),
                ('owners_review', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ongoing', 'Ongoing inspection'),
                            ('completed', 'Completed inspection'),
                            ('pending', 'New inspection'),
                            ('expired', 'Inspection has been scheduled for more than a week without being ongoing or completed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'inspection_verdict',
                    models.CharField(
                        choices=[
                            ('great', 'Average rating above 90 percentile'),
                            ('good', 'Average rating above 60 percentile up to 89'),
                            ('fair', 'Average rating above 40 percentile up to 60'),
                            ('bad', 'Average rating below 39 percentile'),
                        ],
                        default='bad',
                        help_text='Verdict of the inspection after taking into account all the stages and their scores. should be calculated by the system',
                        max_length=10,
                    ),
                ),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.car')),
                (
                    'inspection_assigner',
                    models.ForeignKey(
                        help_text='The user who assigned this inspection to the inspector. should be set automatically',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inspections_assigned',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'inspector',
                    models.ForeignKey(
                        help_text='The person to undertake this inspection',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inspections',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('transaction', 'transaction'),
                    ('trade_unit', 'trade_unit'),
                    ('disbursement', 'disbursement'),
                    ('car_creation', 'car_creation'),
                    ('new_user', 'new user'),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 15, 20, 25, 882766, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='InspectionStage',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(choices=[(20, 'Good'), (10, 'Fair'), (0, 'Poor')])),
                ('part_name', models.CharField(max_length=50)),
                (
                    'stage_name',
                    models.CharField(
                        choices=[
                            ('generic', 'Generic'),
                            ('exterior', 'Exterior'),
                            ('glass', 'Glass'),
                            ('wheels', 'Wheels'),
                            ('under_body', 'Underbody'),
                            ('under_hood', 'Underhood'),
                            ('interior', 'Interior'),
                            ('electrical_systems', 'Electricalsystems'),
                            ('road_test', 'Roadtest'),
                        ],
                        max_length=40,
                    ),
                ),
                ('review', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.inspections')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
