# Generated by Django 3.2.4 on 2022-07-31 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0080_auto_20220731_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 15, 21, 0, 704554, tzinfo=utc), editable=False),
        ),
    ]
