# Generated by Django 3.2.4 on 2022-08-02 22:12

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0082_alter_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='entity_type',
            field=models.CharField(
                choices=[
                    ('car_product', 'Pictures of a car on the sales platform'),
                    ('car', 'car picture'),
                    ('merchant', 'user profile picture'),
                    ('trade', 'Trade pictures of a car'),
                    ('car_inspection', 'Car inspection pictures'),
                    ('feature', 'Picture of a feature of a car'),
                    ('inspection_report', 'Pdf report of an inspected vehicle'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='bought_price',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                help_text='potential cost of  purchasing the car offered by the seller. this should be changed to reflect the actual cost of the car when it is bought',
                max_digits=10,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(
                choices=[
                    ('failed_inspection', 'Failed Inspection'),
                    ('inspected', 'inspected'),
                    ('available', 'available for trading and sale'),
                    ('ongoing_trade', 'Car is an ongoing trade'),
                    ('bought', 'bought'),
                    ('sold', 'sold'),
                    ('new', 'New car waiting to be inspected'),
                    ('archived', 'Archived'),
                ],
                default='new',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 22, 42, 37, 793602, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transactionpin',
            name='device_serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='transactionpin',
            unique_together={('device_serial_number', 'pin')},
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name='modified'
                    ),
                ),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
