# Generated by Django 3.2.4 on 2022-08-02 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0083_auto_20220802_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 22, 43, 18, 985093, tzinfo=utc), editable=False),
        ),
    ]
