name: Deploy

on:
  push:
    branches:
      - master-disabled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./carpadi-1ddb6-firebase-adminsdk-x4sa4-ef6624c208.json
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
#          deploy ....
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Must be unique in Heroku
          docker_options: "--no-cache"
          dockerfile_directory: ./
          process_type: web
