on:
  push:
    branches:
      - master
name: Deploy to staging
jobs:
  build:
    name: build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - name: Get next version
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          # retry_on: error
          command: |
            yarn install
            npx semantic-release --dry-run
            cat ./artifacts/.VERSION >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Docker Build & Push to Container Registry
        run: |
          ls
          
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          base64 -d <<< "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > carpadi-google-cred.json
          base64 -d <<< "${{ secrets.ENVIRONMENT }}" > .env
          docker build --no-cache -t olalekanadebari/carpadi-api:$NEXT_VERSION .
          if [ ${{ github.ref }} == "refs/heads/master" ]; then
            docker image tag  olalekanadebari/carpadi-api:$NEXT_VERSION olalekanadebari/carpadi-api:latest
          fi
          docker image push --all-tags  olalekanadebari/carpadi-api
          docker logout
        env:
          NEXT_VERSION: ${{  env.NEXT_VERSION }}

      - name: Release
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          # retry_on: error
          command: |
            # yarn install
            npx semantic-release
            cat ./artifacts/.VERSION
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: olalekanadebari/carpadi-api:latest
          IMAGE_TAG: ${NEXT_VERSION}
          CONTAINER_NAME: "carpadi-api"
        with:
          host: ${{ secrets.SSH_STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
#          key: ${{secrets.SSH_PEM}}
          port: ${{ secrets.SSH_PORT }}
          envs: IMAGE_NAME,IMAGE_TAG,CONTAINER_NAME
          script: |
              cd ~/
              docker-compose down --rmi all
              docker-compose up -d

# jdghf;akjfgbjkfb